Tab.links
JiscMonitor/monitor-uk pull request #59
Opened 2016-10-17 10:30 UTC by josebarata

[#132239387] Modify tabs & links
+Switched submodule to use JiscMonitor magnificent-octopus

2016-10-17 13:27 UTC, tharglet requested changes

2016-10-17 13:27 UTC, tharglet commented on config/service.py
> +            "anonymous": False
Shouldn't these tabs show all the time and not require auth? This choice seems wrong.

2016-11-03 10:34 UTC, tharglet commented
@josebarata conflict, also my question is still outstanding?

2016-11-09 13:35 UTC, josebarata commented on config/service.py
> +            "anonymous": False
As added in pivotal tracker: The answer is Yes. However removing or changing the auth property to False doesn't produce any results. Will need further analysis.

2016-11-16 16:38 UTC, josebarata commented
Changes were made! The new tabs are now available if the user is not logged in! Ready for another pull review!

2016-11-18 09:54 UTC, adam-rehin commented
Changes look ok on paper - I'm assuming the functionality is as required. I note there is a merge conflict to resolve with magnificent-octopus (sub-module?) version.

2016-11-18 10:31 UTC, josebarata commented
Resolved. Should I merge it?

2016-11-18 14:08 UTC, merged